# Create environment:
# $ conda env create --force

name: dl
channels:
  - conda-forge
  - damianavila82
dependencies:
  - python = 3.6
  - tensorflow >= 1.0
  - keras >= 2.0
  - pillow >= 4.0
  - ipython
  - jupyter
  - anaconda
  - matplotlib
  - seaborn
  - plotly
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - h5py
  - requests
  - setuptools
  - pip
  - pip:
    - rise
    - pygame
    - hyperas
    - pydot
    - pydot-ng
    - nbbrowserpdf
    - ipy-table
